extends: "react-app"

globals:
  __dirname: false
  graphql: false
  process: false

plugins:
- react-hooks

rules:
  import/first: 0
  no-use-before-define: 0
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn